"use client"

import { useState, useEffect } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Calculator, Download } from "lucide-react"
import { useToast } from "@/hooks/use-toast"

interface MaterialEstimate {
  cement: { bags: number; cost: number }
  steel: { kg: number; cost: number }
  bricks: { count: number; cost: number }
  sand: { cft: number; cost: number }
  aggregate: { cft: number; cost: number }
  total: number
}

export function MaterialCalculator() {
  const [area, setArea] = useState(1500)
  const [floors, setFloors] = useState(2)
  const [estimate, setEstimate] = useState<MaterialEstimate | null>(null)
  const [projectName, setProjectName] = useState("My Project")
  const { toast } = useToast()

  useEffect(() => {
    calculateMaterials()
  }, [])

  const calculateMaterials = () => {
    const builtUpArea = area * floors

    // Standard calculations based on industry norms
    const cementBags = Math.ceil(builtUpArea * 0.4)
    const steelKg = Math.ceil(builtUpArea * 4.5)
    const brickCount = Math.ceil(builtUpArea * 8)
    const sandCft = Math.ceil(builtUpArea * 1.25)
    const aggregateCft = Math.ceil(builtUpArea * 1.5)

    const cementCost = cementBags * 400
    const steelCost = (steelKg / 1000) * 70000
    const brickCost = brickCount * 8
    const sandCost = sandCft * 70
    const aggregateCost = aggregateCft * 45

    setEstimate({
      cement: { bags: cementBags, cost: cementCost },
      steel: { kg: steelKg, cost: steelCost },
      bricks: { count: brickCount, cost: brickCost },
      sand: { cft: sandCft, cost: sandCost },
      aggregate: { cft: aggregateCft, cost: aggregateCost },
      total: cementCost + steelCost + brickCost + sandCost + aggregateCost,
    })
  }

  const formatCurrency = (n: number) =>
    new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n)

  const exportToPDF = async () => {
    if (!estimate) return

    try {
      const { jsPDF } = await import("jspdf")

      const pdf = new jsPDF()
      const currentUser = JSON.parse(localStorage.getItem("user") || '{"name":"User"}')
      const currentDate = new Date().toLocaleDateString()

      // Header
      pdf.setFontSize(20)
      pdf.setTextColor(59, 130, 246) // Primary color
      pdf.text("Material Estimate Report", 105, 20, { align: "center" })

      // Project Info
      pdf.setFontSize(12)
      pdf.setTextColor(0, 0, 0)
      pdf.text(`Project Name: ${projectName}`, 20, 40)
      pdf.text(`Date: ${currentDate}`, 20, 48)
      pdf.text(`Prepared By: ${currentUser.name}`, 20, 56)
      pdf.text(`Plot Area: ${area} sqft`, 20, 64)
      pdf.text(`Number of Floors: ${floors}`, 20, 72)

      // Line separator
      pdf.setDrawColor(200, 200, 200)
      pdf.line(20, 78, 190, 78)

      // Material Breakdown Header
      pdf.setFontSize(14)
      pdf.setTextColor(59, 130, 246)
      pdf.text("Material Breakdown", 20, 88)

      // Material Details
      pdf.setFontSize(11)
      pdf.setTextColor(0, 0, 0)
      let yPos = 100

      const materials = [
        { name: "Cement", quantity: `${estimate.cement.bags} bags`, cost: formatCurrency(estimate.cement.cost) },
        { name: "Steel", quantity: `${estimate.steel.kg} kg`, cost: formatCurrency(estimate.steel.cost) },
        {
          name: "Bricks",
          quantity: `${estimate.bricks.count.toLocaleString()} nos`,
          cost: formatCurrency(estimate.bricks.cost),
        },
        { name: "Sand", quantity: `${estimate.sand.cft} cft`, cost: formatCurrency(estimate.sand.cost) },
        { name: "Aggregate", quantity: `${estimate.aggregate.cft} cft`, cost: formatCurrency(estimate.aggregate.cost) },
      ]

      materials.forEach((material) => {
        pdf.setFontSize(11)
        pdf.text(material.name, 20, yPos)
        pdf.text(material.quantity, 80, yPos)
        pdf.text(material.cost, 140, yPos)
        yPos += 10
      })

      // Total Cost
      pdf.line(20, yPos, 190, yPos)
      yPos += 10
      pdf.setFontSize(14)
      pdf.setTextColor(59, 130, 246)
      pdf.text("Total Material Cost:", 20, yPos)
      pdf.text(formatCurrency(estimate.total), 140, yPos)

      // Footer
      pdf.setFontSize(9)
      pdf.setTextColor(128, 128, 128)
      pdf.text("Generated by SIID - Smart Integrated Infrastructure Design", 105, 280, { align: "center" })
      pdf.text("This is a computer-generated estimate. Actual costs may vary.", 105, 285, { align: "center" })

      // Save PDF
      pdf.save(`Material-Estimate-${projectName}-${currentDate}.pdf`)

      toast({
        title: "PDF Exported",
        description: "Material estimate has been downloaded successfully",
      })
    } catch (error) {
      console.error("PDF Export Error:", error)
      toast({
        title: "PDF Export Failed",
        description: "Unable to export PDF. Please try again.",
        variant: "destructive",
      })
    }
  }

  return (
    <Card className="p-6 border-border">
      <div className="flex items-center gap-2 mb-6">
        <Calculator className="w-5 h-5 text-primary" />
        <h3 className="text-lg font-semibold">Material Calculator</h3>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div>
            <Label>Project Name</Label>
            <Input
              type="text"
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
              placeholder="Enter project name"
            />
          </div>
          <div>
            <Label>Plot Area (sqft)</Label>
            <Input type="number" value={area} onChange={(e) => setArea(Number(e.target.value))} min={100} max={50000} />
          </div>
          <div>
            <Label>Number of Floors</Label>
            <Input type="number" value={floors} onChange={(e) => setFloors(Number(e.target.value))} min={1} max={10} />
          </div>
          <Button onClick={calculateMaterials} className="w-full">
            Calculate Materials
          </Button>
        </div>

        {estimate && (
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <Card className="p-3 bg-muted">
                <div className="text-xs text-muted-foreground">Cement</div>
                <div className="font-semibold">{estimate.cement.bags} bags</div>
                <div className="text-sm text-primary">{formatCurrency(estimate.cement.cost)}</div>
              </Card>
              <Card className="p-3 bg-muted">
                <div className="text-xs text-muted-foreground">Steel</div>
                <div className="font-semibold">{estimate.steel.kg} kg</div>
                <div className="text-sm text-primary">{formatCurrency(estimate.steel.cost)}</div>
              </Card>
              <Card className="p-3 bg-muted">
                <div className="text-xs text-muted-foreground">Bricks</div>
                <div className="font-semibold">{estimate.bricks.count.toLocaleString()}</div>
                <div className="text-sm text-primary">{formatCurrency(estimate.bricks.cost)}</div>
              </Card>
              <Card className="p-3 bg-muted">
                <div className="text-xs text-muted-foreground">Sand</div>
                <div className="font-semibold">{estimate.sand.cft} cft</div>
                <div className="text-sm text-primary">{formatCurrency(estimate.sand.cost)}</div>
              </Card>
            </div>
            <Card className="p-4 bg-primary/10 border-primary">
              <div className="text-sm text-muted-foreground">Total Material Cost</div>
              <div className="text-2xl font-bold text-primary">{formatCurrency(estimate.total)}</div>
            </Card>
            <Button variant="outline" className="w-full bg-transparent" size="sm" onClick={exportToPDF}>
              <Download className="w-4 h-4 mr-2" />
              Export Estimate
            </Button>
          </div>
        )}
      </div>
    </Card>
  )
}
